#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIDI-Pitch
version:      0.5
version_from: lib/MIDI/Pitch.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
